# **NUMPY**

Numpy is short for Numerical Python. That means it's a Python library that allows us to perform numerical operations.

The basic building block of Numpy is arrays, or an ndarray. An array is a grid of values of the same type and is indexed by a tuple of non-negative integers. A tuple of non negative integers is simply something like this: [1,2]. This means the array is one dimensional with two elements. Simply put, it has 1 column and 2 rows.

## Key Features of arrays
1. Homogeneous: All elements in a NumPy array must be of the same type.
2. Fixed Size: The size of a NumPy array is fixed at the time of creation.
3. Multidimensional: Arrays can have multiple dimensions (1D, 2D, 3D, etc.).

Arrays are faster than lists in Python because of the following reasons:
1. They are homogeneous. Because an array can only have items of the same data type, it's easier to work this kind of data than lists which can contain any type of data.
2. Element wise operations - By virtue of arrays being of the same data type, you can easily perform operations on them like addition, multiplication e.t.c, at once as opposed to step by step, or iterations like in lists.

What is described above is what is called vectorization. In Python vectorization describes the absence of any explicit looping, indexing, etc, in the code.

### Advantages of vectorization:

1. vectorized code is more concise and easier to read

2. fewer lines of code generally means fewer bugs the code more closely resembles standard mathematical notation (making it easier, typically, to correctly code mathematical constructs)
3. vectorization results in more “Pythonic” code. Without vectorization, our code would be littered with inefficient and difficult to read for loops.

## Creating Arrays

Arrays can be created from lists, tuples, dictionaries e.t.c or using numpy functions.

In [2]:
import numpy as np

## Creating arrays from lists
list1 = [1,2,3,4,5]
list1_array = np.array(list1)
list1_array

array([1, 2, 3, 4, 5])

In [6]:
## Using numpy functions

a = np.zeros((2, 3))  # Array of zeros

b = np.ones((2, 3))  # Array of ones

c = np.eye(3)  # Identity matrix

d = np.arange(10)  # Array of integers from 0 to 9

e = np.linspace(0, 1, 5)  # 5 evenly spaced numbers from 0 to 1

print("This is the first array", a)
print("\n This is the second array", b)
print("\n This is the third array", c)
print("\n This is the fourth array", d)
print("\n This is the fifth array", e)

This is the first array [[0. 0. 0.]
 [0. 0. 0.]]

 This is the second array [[1. 1. 1.]
 [1. 1. 1.]]

 This is the third array [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 This is the fourth array [0 1 2 3 4 5 6 7 8 9]

 This is the fifth array [0.   0.25 0.5  0.75 1.  ]


### Operations on arrays

In [7]:
## Element-wise operations:

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

c = a + b  # Element-wise addition
d = a * b  # Element-wise multiplication

print("This is addition", c)
print("This is multiplication", d)

This is addition [ 6  8 10 12]
This is multiplication [ 5 12 21 32]


##

```
# This is formatted as code
```

Array slicing and indexing:

In [8]:
## Array slicing and indexing:

a = np.array([1, 2, 3, 4, 5])

print("First element is", a[0])  # First element
print("Elements from index 1 to 2", a[1:3])  # Elements from index 1 to 2
print("First three elements are", a[:3])  # First three elements
print("Every second element", a[::2])  # Every second element

First element is 1
Elements from index 1 to 2 [2 3]
First three elements are [1 2 3]
Every second element [1 3 5]


## Array Dimensions


In [10]:
# 0-D array - scalar
arr0 = np.array(42)
print("This is a 0-dimension array", arr0)
# 1-D array
arr1 = np.array([1, 2, 3, 4, 5])
print("This is a 1-dimensional array", arr1)

# 2-D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("This is a 2-dimensional array", arr2)

# 3-D array - An array of 2D arrays
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print("This is a 3-dimensional array", arr3)

This is a 0-dimension array 42
This is a 1-dimensional array [1 2 3 4 5]
This is a 2-dimensional array [[1 2 3]
 [4 5 6]]
This is a 3-dimensional array [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### Creating an n-dimensional array

In [12]:
## We use ndmin to specify the dimensions of an array

# We use ndmin to specify the dimensionality of an array
fashion_array = np.array([['MEC','Maybelline','l\'oral Paris','Sephora','Fenty']], ndmin = 2)
print("This is the fashion_array", fashion_array)

## We use ndim to check the dimensionality of an array

print("This is the number of dimensions", fashion_array.ndim)

This is the fashion_array [['MEC' 'Maybelline' "l'oral Paris" 'Sephora' 'Fenty']]
This is the number of dimensions 2


## EXERCISES

## Exercise 1

Create an array of shape 5 by 4 from a function that takes in a start year and returns elements 12 years from the previous element. Example.

In [15]:
## Solution 1

def year12(start_year,size,values):
  start_value = start_year
  step_size = size
  num_values = values

  # Generate the array
  new_array = np.arange(start_year , start_value + step_size * num_values, step_size)

  # Reshape the array into a 5 by 4 shape
  reshaped_array = new_array.reshape((5, 4))
  return reshaped_array

year12(2023,12,20)

array([[2023, 2035, 2047, 2059],
       [2071, 2083, 2095, 2107],
       [2119, 2131, 2143, 2155],
       [2167, 2179, 2191, 2203],
       [2215, 2227, 2239, 2251]])

In [16]:
## Solution 2

def year(start_year):
  years = [[],[],[],[],[]]
  for i in years:
    counter = 0
    while counter < 4:
      counter+=1
      i.append(start_year)
      start_year+=12
  return np.array(years)

year(2023)


array([[2023, 2035, 2047, 2059],
       [2071, 2083, 2095, 2107],
       [2119, 2131, 2143, 2155],
       [2167, 2179, 2191, 2203],
       [2215, 2227, 2239, 2251]])

## Exercise 2

Using Pythagoras' Theorem, work out the hypotenuse of a triangle that with length as 3m and height as 4m. Save the measurements to the sides in a 1D array. c=√(a^2+b^2)

Use at least two methods to find the hypotenuse.

# Bonus concepts

Linspace vs arange in numpy
linspace generates evenly spaced numbers over a specified interval. The interval is calculated automatically based on the specified number of values to generate.

arange generates values within a specified range with a given step size. [The interval has to be specified]

In [22]:
## Solution 1

def hypotenuse(a,b):
  c = (a**2 + b**2)**0.5
  return np.array([a,b,c], dtype=int)

hypotenuse(4,3)

array([4, 3, 5])

In [23]:
## Solution 2

def hypotenuse2 (a,b):
  a = np.array([a])
  b = np.array([b])

  c = np.hypot(a, b)
  print(c)

hypotenuse2(3,4)

[5.]
